### ISSUE TITLE
POD Error in mysql.pm results in failed `make test`

### ISSUE THREAD

**Issue by dwwalker** [perl5-dbi/DBD-mysql#428] opened 2024-06-02 01:42 UTC
### DBD::mysql version

DBD-mysql-5.005

### MySQL client version

8.0.36

### Server version

 8.0.36-0ubuntu0.22.04.1 (Ubuntu)

### Operating system version

Ubuntu 22.04.4 LTS

### What happened?

make test failed on `t/pod.t` with:

~~~
#   Failed test 'POD test for blib/lib/DBD/mysql.pm'
#   at /home/starman/perl5/perlbrew/perls/perl-5.36.3/lib/site_perl/5.36.3/Test/Pod.pm line 184.
# blib/lib/DBD/mysql.pm (1350): You forgot a '=back' before '=head1'
# Looks like you failed 1 test of 3.
~~~

### Other information

Adding the missing `=back` before line 1350 fixes the issue

**Comment by dwwalker** [comment] 2024-06-02 01:56
replicate using `podchecker`:

~~~
$ podchecker DBD-mysql-5.005/lib/DBD/mysql.pm 
*** ERROR: You forgot a '=back' before '=head1' at line 1350 in file DBD-mysql-5.005/lib/DBD/mysql.pm
DBD-mysql-5.005/lib/DBD/mysql.pm has 1 pod syntax error.
~~~

**Comment by dveeden** [comment] 2024-06-02 05:16
I think this is a duplicate of #426

**Closed** 2024-06-02 05:17 UTC
Labels: bug
