### ISSUE TITLE
Installing on a latest Mac

### ISSUE THREAD

**Issue by davehodg** [perl5-dbi/DBD-mysql#260] opened 2018-09-04 19:41 UTC
I'm installing per the instructions in the ::INSTALL docs with MySQL8 on OSX 10.13.6:

```
# perl Makefile.PL --mysql_config=/usr/local/mysql-8.0.12-macos10.13-x86_64/bin/mysql_config
# export DYLD_LIBRARY_PATH=/usr/local/mysql-8.0.12-macos10.13-x86_64/lib/
```

I'm getting a not unexpected in make test:

```
#   Failed test 'use DBD::mysql;'
#   at t/00base.t line 15.
#     Tried to use 'DBD::mysql'.
#     Error:  Can't load '/Users/daveh/.cpanm/work/1536089487.33357/DBD-mysql-4.046/blib/arch/auto/DBD/mysql/mysql.bundle' for module DBD::mysql: dlopen(/Users/daveh/.cpanm/work/1536089487.33357/DBD-mysql-4.046/blib/arch/auto/DBD/mysql/mysql.bundle, 2): Library not loaded: @rpath/libmysqlclient.21.dylib
#   Referenced from: /Users/daveh/.cpanm/work/1536089487.33357/DBD-mysql-4.046/blib/arch/auto/DBD/mysql/mysql.bundle
#   Reason: image not found at /System/Library/Perl/5.18/darwin-thread-multi-2level/DynaLoader.pm line 194.
#  at t/00base.t line 15.
```

I've tried all the hints I've found online. Ideas?

**Comment by CaptTofu** [comment] 2018-09-13 14:43
Thank you for the report - I will try to reproduce and see how this error comes about.

**Comment by dveeden** [comment] 2018-09-15 13:16
`Library not loaded: @rpath/libmysqlclient.21.dylib`
So looks like it can't find this library while `DYLD_LIBRARY_PATH` is set.

**Comment by dveeden** [comment] 2018-09-15 14:38
This might be a duplicate of #161

**Closed** 2018-09-15 20:56 UTC
Labels: duplicate
