### ISSUE TITLE
4.048 and MariaDB 10.2.18

### ISSUE THREAD

**Issue by graz68a** [perl5-dbi/DBD-mysql#274] opened 2018-10-01 17:53 UTC
Hello

I have 10.2.18-MariaDB MariaDB Server (Centos 7.5) and Perl v5.26.1. When I try to install  DBD::mysql 4.048 I receive following error
No problem installing  4.046_01 . Is it a known issue ?

```
make: Entering directory `/tmp_modules/DBD-mysql-4.048'
cp lib/Bundle/DBD/mysql.pm blib/lib/Bundle/DBD/mysql.pm
cp lib/DBD/mysql.pm blib/lib/DBD/mysql.pm
cp lib/DBD/mysql/INSTALL.pod blib/lib/DBD/mysql/INSTALL.pod
cp lib/DBD/mysql/GetInfo.pm blib/lib/DBD/mysql/GetInfo.pm
Running Mkbootstrap for mysql ()
chmod 644 "mysql.bs"
"/usr/local/perls/perl-5.26.1/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- mysql.bs blib/arch/auto/DBD/mysql/mysql.bs 644
cc -c -I/usr/local/perls/perl-5.26.1/lib/site_perl/5.26.1/x86_64-linux-thread-multi/auto/DBI -I/usr/include/mysql -I/usr/include/mysql/mysql -DDBD_MYSQL_WITH_SSL -g  -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"4.048\" -DXS_VERSION=\"4.048\" -fPIC "-I/usr/local/perls/perl-5.26.1/lib/5.26.1/x86_64-linux-thread-multi/CORE" dbdimp.c
In file included from /usr/include/mysql/mysql.h:60:0,
                 from dbdimp.h:21,
                 from dbdimp.c:15:
dbdimp.c: In function ‘mysql_dr_connect’:
/usr/include/mysql/mariadb_version.h:14:31: error: token ""mariadb-10.2"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-10.2"
                               ^
dbdimp.c:1910:56: note: in expansion of macro ‘MARIADB_BASE_VERSION’
 #if (MYSQL_VERSION_ID >= 50723) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^
/usr/include/mysql/mariadb_version.h:14:31: error: token ""mariadb-10.2"" is not valid in preprocessor expressions
 #define MARIADB_BASE_VERSION  "mariadb-10.2"
                               ^
dbdimp.c:1917:56: note: in expansion of macro ‘MARIADB_BASE_VERSION’
 #if (MYSQL_VERSION_ID >= 50600) && (MYSQL_VERSION_ID < MARIADB_BASE_VERSION)
                                                        ^
dbdimp.c: In function ‘mysql_st_prepare’:
dbdimp.c:3200:24: warning: assignment from incompatible pointer type [enabled by default]
           bind->is_null=      (_Bool*) &(fbind->is_null);
                        ^
make: *** [dbdimp.o] Error 1
make: Leaving directory `/tmp_modules/DBD-mysql-4.048'
```

Thank you
Graziano

**Comment by dveeden** [comment] 2018-10-07 11:42
This is a duplicate of #262, which is fixed in cf752cd10fdd5d8c59f9baff7de6ac651323430e
So 4.049 (not yet released) should work fine.

**Closed by dveeden** 2018-10-07 11:42 UTC
