### ISSUE TITLE
DBD::mysql - mysql.xs.dll not found (Strawberry)

### ISSUE THREAD

**Issue by rtillian** [perl5-dbi/DBD-mysql#318] opened 2019-10-15 09:27 UTC
Connecting with my 
_$dbh = DBI->connect( "DBI:mysql:$dbname:host=$hostname","$username", "$password", ....._
results in 
install_driver(mysql) failed: Can't load 'c:/Strawberry/perl/vendor/lib/auto/DBD/mysql/mysql.xs.dll' for module DBD::mysql: load_file: The module not found  at c:/Strawberry/perl/lib/DynaLoader.pm line 193.

Solution suggested in some places is: 
Copying _C:\strawberry\c\bin\libmysql_.dll_ to _c:\strawberry\perl\vendor\lib\auto\mysql_ does not work in Release Strawberry 5.28.2. - This does not work.

My unusual solution was to copy libmysql_.dll from ActiveState 5.12 (yes, but I was in despair) to c:\strawberry\perl\vendor\lib\auto\mysql - But I think fixing this within the distribution (or Strawberry) should be better.

**Comment by dveeden** [comment] 2019-10-16 07:48
I think this should be fixed in Strawberry. If there are things which can be done in the distribution please let me know. I'm not familiar with Perl on Windows.

**Comment by LeeThompson** [comment] 2021-01-02 21:51
Having this problem on Windows 2008 R2 with Strawberry Perl strawberry-perl-5.30.3.1-64bit

**Comment by rtillian** [comment] 2021-02-04 12:35
Lee, thank you very much!

**Comment by pjcs00** [comment] 2022-04-08 15:54
I am also getting this error: Windows 11, Strawberry Perl 5.32.1.1.  The problem is not that the file is missing: it is in the location specified in the error message, ie c:/Strawberry/perl/vendor/lib/auto/DBD/mysql/mysql.xs.dll . I have tried both 32 and 64 bit Strawberry Perl - both give the same error.

**Comment by hfga** [comment] 2022-10-07 20:28
Mr. [LeeThompson](https://github.com/LeeThompson)'s solution worked for me.

For future reference, libmysql.dll should be copied to "C:/Strawberry/perl/vendor/lib/auto/DBD/mysql/" or to the same folder mysql.xs.dll, if you installed strawberry perl in a location other then the one selected by default.

**Comment by alexandre1** [comment] 2023-01-03 03:39
Hi I was attempting to download mysql-connector-c-6.1.11.zip but could not find any place. I need the mysql.xs.dll

**Comment by dveeden** [comment] 2023-01-03 11:07
> Hi I was attempting to download mysql-connector-c-6.1.11.zip but could not find any place. I need the mysql.xs.dll

This should be available on https://downloads.mysql.com/archives/c-c/

**Comment by genio** [comment] 2023-01-03 13:49
@LeeThompson The reasoning on the `PATH` can be found here: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/11#issuecomment-674433024

**Comment by dveeden** [comment] 2024-11-11 06:56
Closing this as this seems to be a issue with StrawberryPerl (which is likely already fixed) and not an issue with DBD::mysql.

If it is not fixed and needs changes in DBD::mysql then please post more details and we can re-open it.

**Closed by dveeden** 2024-11-11 06:56 UTC
Labels: Windows
